const linkedList = require('./modules/linkedList')
let myLinkedList = linkedList();
myLinkedList.append('node 1')
console.log(myLinkedList.toString())
myLinkedList.prepend('node 0')
console.log(myLinkedList.toString())
myLinkedList.append('node 2')
console.log(myLinkedList.toString())
myLinkedList.append('node 3')
console.log(myLinkedList.toString())
console.table(myLinkedList.pop())
console.log(myLinkedList.toString())
console.log(myLinkedList.size())
console.table(myLinkedList.at(1))
console.table(myLinkedList.head())
console.log(myLinkedList.contains('node 1'))
console.log(myLinkedList.find('node 2'))
console.log(myLinkedList.contains('node 7'))
console.log(myLinkedList.find('node 7'))
myLinkedList.insertAt('node x',0)
console.log(myLinkedList.toString())
myLinkedList.removeAt(3)
console.log(myLinkedList.toString())
