const linkedList = require('./modules/linkedList')
let myLinkedList = linkedList();
myLinkedList.append('node 1')
console.log(myLinkedList.toString())
myLinkedList.prepend('node 0')
console.log(myLinkedList.toString())
myLinkedList.append('node 2')
console.log(myLinkedList.toString())
myLinkedList.append('node 3')
console.log(myLinkedList.toString())
myLinkedList.pop()
console.log(myLinkedList.toString())
console.log(myLinkedList.size())
console.table(myLinkedList.at(2).getData())
console.log(myLinkedList.contains('node 1'))
console.log(myLinkedList.find('node 2'))
console.log(myLinkedList.contains('node 7'))
console.log(myLinkedList.find('node 7'))